import { PermissionConfig } from '../interfaces/auth.interface';

export const PERMISSIONS_CONFIG: PermissionConfig = {
  admin: [
    'user:read',
    'user:write',
    'user:delete',
    'student:read',
    'student:write',
    'student:delete',
    'group:read',
    'group:write',
    'group:delete',
    'session:read',
    'session:write',
    'session:delete',
    'task:read',
    'task:write',
    'task:delete',
    'admin:access',
    'status:read',
    'status:write',
    'status:delete',
    'period:read',
    'period:write',
    'period:delete',
    'orientation:read',
    'orientation:write',
    'orientation:delete',
    'nationality:read',
    'nationality:write',
    'nationality:delete',
    'gender:read',
    'gender:write',
    'gender:delete',
    'frenchlevel:read',
    'frenchlevel:write',
    'frenchlevel:delete',
    'financing:read',
    'financing:write',
    'financing:delete',
    'exitreason:read',
    'exitreason:write',
    'exitreason:delete',
    'exam:read',
    'exam:write',
    'exam:delete',
    'disability:read',
    'disability:write',
    'disability:delete',
    'course:read',
    'course:write',
    'course:delete',
    'continuation:read',
    'continuation:write',
    'continuation:delete',
    'address:read',
    'address:write',
    'address:delete',
    'absence:read',
    'absence:write',
    'absence:delete',
  ],
  teacher: [
    'student:read',
    'student:write',
    'student:delete',
    'group:read',
    'group:write',
    'group:delete',
    'session:read',
    'session:write',
    'session:delete',
    'task:read',
    'task:write',
    'task:delete',
    'teacher:access',
    'self:read',
    'status:read',
    'status:write',
    'status:delete',
    'period:read',
    'period:write',
    'period:delete',
    'orientation:read',
    'orientation:write',
    'orientation:delete',
    'nationality:read',
    'nationality:write',
    'nationality:delete',
    'gender:read',
    'gender:write',
    'gender:delete',
    'frenchlevel:read',
    'frenchlevel:write',
    'frenchlevel:delete',
    'financing:read',
    'financing:write',
    'financing:delete',
    'exitreason:read',
    'exitreason:write',
    'exitreason:delete',
    'exam:read',
    'exam:write',
    'exam:delete',
    'disability:read',
    'disability:write',
    'disability:delete',
    'course:read',
    'course:write',
    'course:delete',
    'continuation:read',
    'continuation:write',
    'continuation:delete',
    'address:read',
    'address:write',
    'address:delete',
    'absence:read',
    'absence:write',
    'absence:delete',
  ],
  user: [
    'self:read',
    'self:write',
  ],
};

// Constantes de sécurité
export const SECURITY_CONFIG = {
  MAX_LOGIN_ATTEMPTS: 5,
  LOCK_TIME: 15 * 60, // 15 minutes en secondes
  RESET_TOKEN_EXPIRY: 24 * 60 * 60, // 24 heures en secondes
  JWT_EXPIRY: '1d',
} as const; 